name: adobe
description: "AI-based image editor"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  image_picker: ^1.2.1
  uuid: ^4.5.2
  receive_sharing_intent: ^1.8.1
  http: ^1.6.0
  html: ^0.15.6
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  image: ^4.5.4
  onnxruntime: ^1.4.1
  intl: ^0.20.2
  google_mlkit_text_recognition: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/dinov2.onnx
    - assets/dinov2.onnx.data
    - assets/texture_centroids.json
    - assets/clip_image_encoder.onnx
    - assets/style_embeddings.json
    - assets/emotion_centroids.json
    - assets/lighting_centroids.json
    - assets/era_centroids.json
    - assets/font_database.json
    - assets/fannet.onnx

  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/GeneralSans-Extralight.otf
          weight: 200
        - asset: assets/fonts/GeneralSans-Light.otf
          weight: 300
        - asset: assets/fonts/GeneralSans-Regular.otf
          weight: 400
        - asset: assets/fonts/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/GeneralSans-Semibold.otf
          weight: 600
