name: creekui
description: "AI-based image editor"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  cryptography: ^2.9.0
  dotted_border: ^2.0.0
  flutter_box_transform: ^0.4.7
  flutter_colorpicker: ^1.1.0
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.3
  google_fonts: ^6.1.0
  google_mlkit_text_recognition: ^0.15.0
  html: ^0.15.6
  http: ^1.6.0
  image_picker: ^1.2.1
  image: ^4.5.4
  intl: ^0.20.2
  onnxruntime: ^1.4.1
  path_provider: ^2.1.5
  path: ^1.9.1
  provider: ^6.1.5+1
  receive_sharing_intent: ^1.8.1
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  undo: ^1.0.1
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/fonts/
    - assets/icons/
    - assets/templates/
    - assets/stylesheet/lighting/
    - assets/stylesheet/material-look/
    - assets/stylesheet/texture/
    - assets/moodboard_blob.png
    - assets/stylesheet_blob.png
    - assets/files_blob.png
    - assets/dinov2.onnx
    - assets/dinov2.onnx.data
    - assets/texture_centroids.json
    - assets/clip_image_encoder.onnx
    - assets/style_embeddings.json
    - assets/emotion_centroids.json
    - assets/lighting_centroids.json
    - assets/era_centroids.json
    - assets/font_database.json
    - assets/fannet.onnx

  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/GeneralSans-Extralight.otf
          weight: 200
        - asset: assets/fonts/GeneralSans-Light.otf
          weight: 300
        - asset: assets/fonts/GeneralSans-Regular.otf
          weight: 400
        - asset: assets/fonts/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/GeneralSans-Semibold.otf
          weight: 600

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
